#pragma once

// VER_DATE format: YEAR, MONTH, DAY, (optional 0/WEEK)

#define VER_COMPANYNAME_STR ""
#define VER_PRODUCTNAME_STR "MCGL Engine"

#define VER_FILEVERSION 0,0,1,1
#define VER_FILEVERSION_STR "0.0.1.1 (2019-06-06)"
#define VER_DATE 2019,6,6,0

#define VER_PRODUCTVERSION VER_FILEVERSION
#define VER_PRODUCTVERSION_STR VER_FILEVERSION_STR
