/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <win32/jni_md.h>
/* Header for class MCGLEngineInterface */

#ifndef _Included_MCGLEngineInterface
#define _Included_MCGLEngineInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MCGLEngineInterface
 * Method:    CreateEngine
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_MCGLEngineInterface_CreateEngine
  (JNIEnv *, jobject);

/*
 * Class:     MCGLEngineInterface
 * Method:    CreateWindow
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_MCGLEngineInterface_CreateWindow
  (JNIEnv *, jobject, jint, jint, jstring);

/*
 * Class:     MCGLEngineInterface
 * Method:    Run
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_MCGLEngineInterface_Run
  (JNIEnv *, jobject);

/*
 * Class:     MCGLEngineInterface
 * Method:    DestroyEngine
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_MCGLEngineInterface_DestroyEngine
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
