/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MCGLEngineInterface */

#ifndef _Included_MCGLEngineInterface
#define _Included_MCGLEngineInterface
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     MCGLEngineInterface
	 * Method:    createEngine
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_MCGLEngineInterface_createEngine
	( JNIEnv *, jobject );

	/*
	 * Class:     MCGLEngineInterface
	 * Method:    destroyEngine
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_MCGLEngineInterface_destroyEngine
	( JNIEnv *, jobject );

	/*
	 * Class:     MCGLEngineInterface
	 * Method:    createWindow
	 * Signature: (IILjava/lang/String;)V
	 */
	JNIEXPORT void JNICALL Java_MCGLEngineInterface_createWindow
	( JNIEnv *, jobject, jint, jint, jstring );

	/*
	 * Class:     MCGLEngineInterface
	 * Method:    updatePlayerPosition
	 * Signature: (DDD)V
	 */
	JNIEXPORT void JNICALL Java_MCGLEngineInterface_updatePlayerPosition
	( JNIEnv *, jobject, jdouble, jdouble, jdouble );

	/*
	 * Class:     MCGLEngineInterface
	 * Method:    updatePlayerCamera
	 * Signature: (DD)V
	 */
	JNIEXPORT void JNICALL Java_MCGLEngineInterface_updatePlayerCamera
	( JNIEnv *, jobject, jdouble, jdouble );

	/*
	 * Class:     MCGLEngineInterface
	 * Method:    run
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_MCGLEngineInterface_run
	( JNIEnv *, jobject );

	/*
	 * Class:     MCGLEngineInterface
	 * Method:    stop
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_MCGLEngineInterface_stop
	( JNIEnv *, jobject );

	/*
	 * Class:     MCGLEngineInterface
	 * Method:    registerKeyEventCallback
	 * Signature: (Ljava/lang/String;)V
	 */
	JNIEXPORT void JNICALL Java_MCGLEngineInterface_registerKeyEventCallback
	( JNIEnv *, jobject, jstring );

	/*
	 * Class:     MCGLEngineInterface
	 * Method:    registerMouseEventCallback
	 * Signature: (Ljava/lang/String;)V
	 */
	JNIEXPORT void JNICALL Java_MCGLEngineInterface_registerMouseEventCallback
	( JNIEnv *, jobject, jstring );

#ifdef __cplusplus
}
#endif
#endif
