#pragma once

#include "Action/Action.h"

#include "Action/AddChunkAction.h"
#include "Action/RemoveChunkAction.h"
#include "Action/AddChunkAction.h"
#include "Action/CloseWindowAction.h"
#include "Action/CreateCameraAction.h"
#include "Action/CreateWindowAction.h"
#include "Action/GetDeltaTimeAction.h"
#include "Action/MoveCameraAction.h"
#include "Action/RegisterBlockTypeAction.h"
#include "Action/RegisterKeyEventCallbackAction.h"
#include "Action/RegisterMouseEventCallbackAction.h"
#include "Action/RegisterStatusEventCallbackAction.h"
#include "Action/RemoveChunkAction.h"
#include "Action/RotateCameraAction.h"
#include "Action/RunAction.h"
#include "Action/SetShaderAction.h"
#include "Action/SetTexturesAction.h"
#include "Action/StopAction.h"
